SETTINGS:
    # 用于按反应任务等的Discord令牌，用于获取表情信息
    DISCORD_TOKEN_FOR_PARSING: ""
    # 用于解析的代理。格式：用户名:密码@IP:端口
    PROXY_FOR_PARSING: ""

    # 并发线程数
    THREADS: 2

    # 任何操作的重试次数
    ATTEMPTS: 5

    # 将账户随机打乱顺序
    SHUFFLE_ACCOUNTS: true

    # 账户范围。
    # 默认值：[0, 0] - 使用所有账户
    # [3, 5] - 仅使用第3、4、5个账户
    # [7, 7] - 仅使用第7个账户
    ACCOUNTS_RANGE: [0, 0]

    # 仅当 ACCOUNTS_RANGE 为 [0, 0] 时生效
    # 指定要使用的具体账户。
    # 默认值：[] - 使用所有账户
    # 示例：[1, 4, 6] - 机器人将仅使用第1、4、6个账户
    EXACT_ACCOUNTS_TO_USE: []

    # 重试之间的暂停时间（秒）
    PAUSE_BETWEEN_ATTEMPTS: [1, 2]

    # 账户之间的暂停时间（秒）
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [1, 2]

    # 操作之间的暂停时间（秒）
    RANDOM_PAUSE_BETWEEN_ACTIONS: [1, 2]

    # 每个账户开始前的随机暂停时间（秒）
    # 以确保所有账户在不同时间启动
    RANDOM_INITIALIZATION_PAUSE: [1, 2]

    # 为更换头像任务使用随机头像
    RANDOM_PROFILE_PICTURES: true


AI_CHATTER:
    # 机器人发送消息的Discord服务器ID
    GUILD_ID: ""

    # 机器人发送消息的Discord频道ID
    CHANNEL_ID: ""

    # 当机器人被询问时，回答或忽略问题的概率（百分比）
    ANSWER_PERCENTAGE: 50

    # 文本中有多少百分比会回复其他用户的消息
    # 其余消息将直接发送到聊天中。
    # 如果为0，机器人不会回复任何人
    # 如果为100，机器人只会回复其他用户的消息。
    REPLY_PERCENTAGE: 50

    # 每个账户要发送的消息数量
    MESSAGES_TO_SEND_PER_ACCOUNT: [3, 5]

    # 消息之间的暂停时间（秒）
    PAUSE_BETWEEN_MESSAGES: [3, 5]

    # 从ChatGPT获取响应后到发送消息到Discord前的暂停时间（秒）
    PAUSE_BEFORE_MESSAGE: [1, 2]


MESSAGE_SENDER:
    # 机器人发送消息的Discord服务器ID
    GUILD_ID: ""

    # 机器人发送消息的Discord频道ID
    CHANNEL_ID: ""

    # 发送后立即删除消息
    DELETE_MESSAGE_INSTANTLY: false

    # 随机发送消息
    SEND_MESSAGES_RANDOMLY: false

    # 每个账户要发送的消息数量。因此每个账户都会发送这个数量的消息
    NUMBER_OF_MESSAGES_TO_SEND: 3

    # 消息之间的暂停时间（秒）
    PAUSE_BETWEEN_MESSAGES: [1, 5]


CHAT_GPT:
    # API密钥列表。机器人将为每条消息随机使用一个API密钥。
    API_KEYS: ["sk-proj-"]
    # 要使用的ChatGPT模型。参考：https://platform.openai.com/docs/models
    MODEL: "gpt-4o"

    # 在某些国家可能需要使用代理访问ChatGPT。
    # 默认值为空。格式：用户名:密码@IP:端口
    PROXY_FOR_CHAT_GPT: ""

DEEPSEEK:
    # API密钥列表。机器人将为每条消息随机使用一个API密钥。
    API_KEYS: ["sk-"]
    # 要使用的ChatGPT模型。参考：https://platform.openai.com/docs/models
    MODEL: "deepseek-chat"

    # 在某些国家可能需要使用代理访问ChatGPT。
    # 默认值为空。格式：用户名:密码@IP:端口
    PROXY_FOR_DEEPSEEK: ""